version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "15667:15667"
    volumes:
      # 使用相对路径挂载，确保路径正确
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/projectmanagement.db  # 使用相对路径
    # 确保容器以root用户运行，避免权限问题
    user: "root"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "15668:80"
    depends_on:
      - backend