version: '3.8'

services:
  backend:
    build:
      context: .
      args:
        - WERKZEUG_VERSION=2.0.1
    ports:
      - "15667:15667"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/projectmanagement
      - SECRET_KEY=your_secret_key_here
      - DEBUG=False
      - FILE_ROOT_DIRECTORY=/app/uploads
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/frontend/dist
      - ./uploads:/app/uploads

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projectmanagement
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
